<a href="https://colab.research.google.com/github/Shrinjoymaiti/pycourse/blob/master/lecture_3_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#E1
Create a 1D numpy array of numbers from 1 to 9 without manually typing numbers.

In [2]:
import numpy as np
arr=np.arange(10) #arange brings out integer values of 10 numbers from 0
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#E2
Extract all odd numbers from the given array

In [29]:
odd=arr[arr%2==1] #any odd num when divided by 2 gives 1 as remainder
odd

array([1, 3, 5, 7, 9])

#E3
Replace all odd numbers in the given array with -1

In [30]:
arr[arr%2==1]=-1 #Replacing odd values with -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

# E4
Conver the given 1D array to 2D array with two rows

In [31]:
x=np.arange(10) #Taking an array from 0 to 9
x_reshaped=np.reshape(x,(2,5)) #(array, order )
x_reshaped

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

# E5
Find common items in a and b

In [32]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
c=np.intersect1d(a,b) #this returns the common values of a and b
c

array([2, 4])

# E6
Get items between 5 and 10 from the given array
a = np.array([2, 6, 1, 9, 10, 3, 27])

In [52]:
a = np.array([2, 6, 1, 9, 10, 3, 27])
a[(a>4) & (a<11)]  #checking for values between 5 and 10 


array([ 6,  9, 10])

#E7
a. Find the sum, max value of all the values in the given numpy array

b. FInd the maximum value in each column in the given array

In [3]:
a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
            [0.54627315, 0.05093587, 0.40067661, 0.55645993],
             [0.12697628, 0.82485143, 0.26590556, 0.56917101]])
sum=a.sum() #this calculates sum of all elements of array a
sum

4.8595784

In [4]:
max_val=a.max() #this finds the max value amongst the values of array a
max_val

0.82485143

# E8
Use a function to multiply all the value of the array by 10

In [6]:
def multiply(): #defining our function
  a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
            [0.54627315, 0.05093587, 0.40067661, 0.55645993],
             [0.12697628, 0.82485143, 0.26590556, 0.56917101]])
  m=10*a #scalar multiplication of array
  return m #returning the desired array after multiplication
multiply()

array([[4.5053314, 1.7296777, 3.4376245, 5.510652 ],
       [5.4627315, 0.5093587, 4.0067661, 5.5645993],
       [1.2697628, 8.2485143, 2.6590556, 5.6917101]])

# E9
Convert Depth column into index of pandas (log_data)

In [34]:
import pandas as pd
url='https://raw.githubusercontent.com/Energy-AI/basic_course/master/Lecture_3/data/log_data_csv.csv?token=AQTTZ5DUK4UU75EZTVNI2QS7MDKAE' #definig url where our exists our desired file
log_data = pd.read_csv(url) #reading csv file
log_data.set_index('DEPTH', inplace= True) #setting depth a index
log_data.head() #this shows first 5 rows of our dataframe

ABDCQF01  ABDCQF02  ABDCQF03  ABDCQF04  ...  ROP  RPCEHM  RPCELM  RT
DEPTH                                          ...                         
145.9       NaN       NaN       NaN       NaN  ...  NaN     NaN     NaN NaN
146.0       NaN       NaN       NaN       NaN  ...  NaN     NaN     NaN NaN
146.1       NaN       NaN       NaN       NaN  ...  NaN     NaN     NaN NaN
146.2       NaN       NaN       NaN       NaN  ...  NaN     NaN     NaN NaN
146.3       NaN       NaN       NaN       NaN  ...  NaN     NaN     NaN NaN

[5 rows x 22 columns]

# E10
Convert 'BS' column of pandas into a numpy array

In [12]:
bs=log_data['BS'] #assigning only BS column to bs
arr=bs.to_numpy() #coverting the values of bs into numpy array
arr

array([36. , 36. , 36. , ...,  8.5,  8.5,  8.5])

# E11
Find the frequency of unique values present in 'BS' column in pandas

In [14]:
log_data['BS'].value_counts() #this returns the frequency of each different element in BS column

17.5000    12469
26.0000    11289
12.2500     4827
8.5000      3800
36.0000      800
12.2283        2
8.5217         1
25.9508        1
17.4696        1
35.9421        1
Name: BS, dtype: int64

# E12
Find the Number of unique values in 'BS' column in pandas

In [15]:
log_data['BS'].nunique()

10

# E13
Find the minimum, 25th percentile, median, 75th percentile and maximum value of 'GR' column in pandas

In [18]:
min=log_data['GR'].min() #this shows the min value of GR column
percentile_25th=log_data['GR'].quantile(0.25) #this shows the 25th percentile of GR column
median=log_data['GR'].median() #this shows the median of GR column
percentile_75th=log_data['GR'].quantile(0.75) #this shows the 75th percentile of GR column
print('Minimum= ' + str(min))
print('25th percentile= ' + str(percentile_25th))
print('Median= ' + str(median))
print('75th percentile= ' + str(percentile_75th))

Minimum= 0.1493
25th percentile= 29.481175
Median= 58.005700000000004
75th percentile= 79.2472


# E14
Replace Bit Size of value 36 to 40 in log_data

In [55]:
log_data['BS']=log_data['BS'].replace([36],40.0) #thsi replaces all 36 to 40 in BS column
log_data['BS']

0        40.0
1        40.0
2        40.0
3        40.0
4        40.0
         ... 
33186     8.5
33187     8.5
33188     8.5
33189     8.5
33190     8.5
Name: BS, Length: 33191, dtype: float64

# E15
Get the column types of the below pandas and delete the column Unnamed: 0

production_data = pd.read_csv('data/prod_data.csv')

In [74]:
production_data = pd.read_csv('https://raw.githubusercontent.com/Energy-AI/basic_course/master/Lecture_3/data/prod_data.csv?token=AQTTZ5DZS2D2BL63WTEOYCS7MDWR6')
del production_data['Unnamed: 0']
production_data

DATEPRD  AVG_DOWNHOLE_PRESSURE  ...   FLOW_KIND  WELL_TYPE
0      2014-04-07                0.00000  ...  production         WI
1      2014-04-08                    NaN  ...  production         OP
2      2014-04-09                    NaN  ...  production         OP
3      2014-04-10                    NaN  ...  production         OP
4      2014-04-11              310.37614  ...  production         OP
...           ...                    ...  ...         ...        ...
15629  2016-09-14                    NaN  ...  production         OP
15630  2016-09-15                    NaN  ...  production         OP
15631  2016-09-16                    NaN  ...  production         OP
15632  2016-09-17                    NaN  ...  production         OP
15633  2016-09-18                    NaN  ...   injection         WI

[15634 rows x 16 columns]

# E16
Convert the DATEPRD column into date-time format and replace DATEPRD column as pandas index

In [76]:
production_data['DATEPRD']=pd.to_datetime(production_data['DATEPRD']) #this converts DATEPRD which was initially dtype= object into dtype=datetime64[ns]
production_data['DATEPRD']

0       2014-04-07
1       2014-04-08
2       2014-04-09
3       2014-04-10
4       2014-04-11
           ...    
15629   2016-09-14
15630   2016-09-15
15631   2016-09-16
15632   2016-09-17
15633   2016-09-18
Name: DATEPRD, Length: 15634, dtype: datetime64[ns]

In [77]:
production_data.set_index('DATEPRD', inplace=True)
production_data

AVG_DOWNHOLE_PRESSURE  ...  WELL_TYPE
DATEPRD                            ...           
2014-04-07                0.00000  ...         WI
2014-04-08                    NaN  ...         OP
2014-04-09                    NaN  ...         OP
2014-04-10                    NaN  ...         OP
2014-04-11              310.37614  ...         OP
...                           ...  ...        ...
2016-09-14                    NaN  ...         OP
2016-09-15                    NaN  ...         OP
2016-09-16                    NaN  ...         OP
2016-09-17                    NaN  ...         OP
2016-09-18                    NaN  ...         WI

[15634 rows x 15 columns]

# E17
Groupby Pandas based on year and find the sum of all individual columns

In [84]:
production_data.groupby(pd.Grouper(freq='Y')).sum() #Grouper allows us to specify additional instruction to groupby by specifying the frequency(=year) of target selection

AVG_DOWNHOLE_PRESSURE  ...   BORE_WI_VOL
DATEPRD                            ...              
2007-12-31               0.000000  ...  0.000000e+00
2008-12-31          126332.310680  ...  2.417770e+06
2009-12-31          171879.218917  ...  4.392198e+06
2010-12-31          160502.923169  ...  4.569394e+06
2011-12-31           83850.168072  ...  3.442446e+06
2012-12-31           78690.519824  ...  2.975214e+06
2013-12-31          127489.850406  ...  3.453761e+06
2014-12-31          317179.952517  ...  3.825493e+06
2015-12-31          349952.670812  ...  3.201627e+06
2016-12-31          216721.126936  ...  2.052229e+06

[10 rows x 12 columns]

METHOD 2:

In [89]:
production_data.groupby(lambda y: (y.year)).sum() #This retruns date index in the foem of year only

AVG_DOWNHOLE_PRESSURE  ...   BORE_WI_VOL
2007               0.000000  ...  0.000000e+00
2008          126332.310680  ...  2.417770e+06
2009          171879.218917  ...  4.392198e+06
2010          160502.923169  ...  4.569394e+06
2011           83850.168072  ...  3.442446e+06
2012           78690.519824  ...  2.975214e+06
2013          127489.850406  ...  3.453761e+06
2014          317179.952517  ...  3.825493e+06
2015          349952.670812  ...  3.201627e+06
2016          216721.126936  ...  2.052229e+06

[10 rows x 12 columns]